### ISSUE TITLE
sqlc hallucinates ambiguous column references when no ambiguity exists 

### ISSUE THREAD

**Issue by andrewmbenton** [sqlc-dev/sqlc#2538]
### Version

1.19.1

### What happened?

Discovered while working on https://github.com/sqlc-dev/sqlc/pull/2537, sqlc returns an ambiguous column reference error for some queries which run fine with psql. See examples below.

To fix we'll need to update `findColumnForRef()` in `output_columns.go` I believe.

### Relevant log output

```shell
query.sql:9:1: column reference "name" is ambiguous: if you want to skip this validation, set 'strict_order_by' to false
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
SELECT a.name
FROM authors a JOIN authors b ON a.id = b.id
ORDER BY name;

SELECT a.name AS name
FROM authors a JOIN authors b ON a.id = b.id
ORDER BY name;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/8e9c3fa8f50201433c489b118a731130a7011574ec53d27bbe460eb1978f2f13

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by andrewmbenton** [comment]
The urgency on resolving this isn't super high. The obvious workaround is to just fully qualify the column names in your order by clauses. In both queries above, using `ORDER BY a.name` resolves the sqlc confusion about ambiguity.

**Comment by kyleconroy** [comment]
Fixed as of v1.22.0 https://play.sqlc.dev/p/7daff5ad5a1573f1f3c1d8604e804d83af316633f7ab1edcded7c57c9bd3240b

**Comment by andrewmbenton** [comment]
Still broken if you use the postgresql or mysql engines: https://play.sqlc.dev/p/3d1c2485fb8a777557b4de50bb3f7d60e17ec1a8fdcbdb42d674a5b5eae967ad

**Comment by kyleconroy** [comment]
This is fixed in [v1.23.0](https://docs.sqlc.dev/en/latest/reference/changelog.html#v1-23-0) by enabling the [database-backed query analyzer](https://docs.sqlc.dev/en/latest/howto/generate.html#enhanced-analysis-with-managed-databases). We added a [test case](https://github.com/sqlc-dev/sqlc/tree/main/internal/endtoend/testdata/join_order_by/postgresql/pgx) for this issue so it won’t break in the future.

You can play around with the [working example on the playground](https://play.sqlc.dev/p/599992bfd7feb99c085c7e3b19222bf6f094b5125daa59c323c66b2c1e9025b6)
