### ISSUE TITLE
Resolving references to CTE Columns fails

### ISSUE THREAD

**Issue by simonklee** [sqlc-dev/sqlc#3585]
### Version

1.27.0

### What happened?

Resolving references to multiple CTE's with arguments fails.

This is a duplicate of #3219, but 3219 has been closed even thought the issue still persists and the relevant PR is not merged.

PR to fix this issue: https://github.com/sqlc-dev/sqlc/pull/3220

### Relevant log output

```shell
sqlc generate failed.
# package 
query.sql:5:28: table alias "t1_ids" does not exist
```

### Database schema

```sql
CREATE TABLE t1
(
    id SERIAL NOT NULL PRIMARY KEY
);
```

### SQL queries

```sql
-- name: CTERef :one
2
WITH t1_ids AS (
3
    SELECT id FROM t1
4
)
5
SELECT * FROM t1_ids WHERE t1_ids.id = sqlc.arg('id');
```

### Configuration

```yaml
{
2
  "version": "2",
3
  "sql": [{
4
    "schema": "schema.sql",
5
    "queries": "query.sql",
6
    "engine": "postgresql",
7
    "gen": {
8
      "go": {
9
        "out": "db"
10
      }
11
    }
12
  }]
13
}
14
​
```

### Playground URL

https://play.sqlc.dev/p/9048b486f822c300301650867612e42bef8f8d512dfd12d84ad3a4cd210f4ef7

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by michaelgrijalva-resim** [comment]
If anyone else runs into this issue and lands on this page, I found it usually works if you explicitly annotate the appropriate type on the sqlc argument:

```sql
-- name: CTERef :one
WITH t1_ids AS (
    SELECT id FROM t1
)
SELECT * FROM t1_ids WHERE t1_ids.id = sqlc.arg('id')::uuid;
--                                                   ^^^^^^
```

This makes sqlc happy for now, until the above fix is merged.

**Comment by mem** [comment]
I have a similar issue, but the workaround suggested in this case does not work.

https://play.sqlc.dev/p/3df2d3f54eff7ef74e32ffca38be69ddd9a3dc7058cbe7ae9274007e05909236

The SQL in the link is silly, as I have reduced the case as much as possible.

The actual query is trying to retrieve a single record with some conditions and insert a modified version of the same record using input provided by the user.

**Comment by ednmechrock** [comment]
Still getting this issue on 24/3/2025 using sqlc v1.28.0
Annotation as above (https://github.com/sqlc-dev/sqlc/issues/3585#issuecomment-2486992260) also still working as a temp fix.
